config/routes.rb
Rails.application.routes.draw do

resources :posts do
  resources :comments
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :post, dependent: :destroy

end

app/models/post.rb
class Post < ActiveRecord::Base

	has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
		@post = Post.find(params[:post_id])
		@comment = Comment.new
	end

	def create
		@post = Post.find(params[:post_id])
		@post.comments.create(comment_params)
		redirect_to posts_path
	end

	def comment_params
		params.require(:comment).permit(:thoughts)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@post = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.create(post_params)
		redirect_to '/posts'
	end

	def post_params
		params.require(:post).permit(:title, :url)
	end

	def show
		@post = Post.find(params[:id])
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		flash[:notice] = 'Post deleted successfully'
		redirect_to '/posts'
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/new.html.erb
<%= @post.title %>
<%= @post.url %>

<%= form_for [@post, @comment] do |f| %>
	<%= f.label :thoughts %>
	<%= f.text_area :thoughts %>
	<%= f.submit 'Save' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= notice %>
<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<a href="/posts/new">Submit a new link</a><br>

<% if @post.any? %>
<% @post.each do |post| %>
<%= link_to "#{post.title}", post.url %><br>
<%= post.url %>
<%= link_to "Delete", post_path(post), method: :delete %>
<%= link_to "Comment", new_post_comment_path(post) %>
<%= link_to "Comments", post_path(post) %>
<h3>Comments</h3>
<% if post.comments.any? %>
<ul>
	<% post.comments.each do |comment| %>
	<li>
		<%= comment.thoughts %>
	</li>
	<% end %>
	<ul>
		<% else %>
		<p>No comments.</p>
		<% end %>
<% end %>
<% else %>
<h1>No Posts</h1>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :url %>
<%= f.text_field :url %>
<%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<%= @post.title %><br>
<%= @post.url %>

<% if @post.comments.any? %>
	<ul>
		<% post.comments.each do |comment| %>
		<li>
			<%= comment.thoughts %>
		</li>
		<% end %>
	</ul>
	<% else %>
	<p>No Comments</p>
<% end %>